### ISSUE TITLE
not enough arguments in call to redshift.NewRedshift

### ISSUE THREAD

**Issue by harlow** [Clever/postgres-to-redshift#34]
When calling `NewRedshift` from main.go there are no args passed:

``` go
if *updateRS {
        r, err := redshift.NewRedshift()
```

https://github.com/Clever/postgres-to-redshift/blob/master/main.go#L45

However, from the `redshifter` library it looks like all the connection args are required:

``` go
func NewRedshift(host, port, db, user, password string, timeout int, s3Info S3Info) (*Redshift, error) {
```

https://github.com/Clever/postgres-to-redshift/blob/master/vendor/github.com/Clever/redshifter/redshift/redshift.go#L79

**Comment by schimmy** [comment]
Hey @harlow this should be fixed by https://github.com/Clever/postgres-to-redshift/pull/35, but please let us know if that's not the case. Thank you for pointing it out!
